<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7898" started-at="2017-05-30T04:40:01Z" finished-at="2017-05-30T04:40:09Z">
    <groups>
      <group name="functest">
        <method signature="WolframCloudTestSuite.siteLaunch()[pri:1, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="siteLaunch" class="WolframTestSuite.WolframCloudTestSuite"/>
        <method signature="WolframCloudTestSuite.tryLogin()[pri:2, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="tryLogin" class="WolframTestSuite.WolframCloudTestSuite"/>
        <method signature="WolframCloudTestSuite.tryNotebook()[pri:5, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="tryNotebook" class="WolframTestSuite.WolframCloudTestSuite"/>
        <method signature="WolframCloudTestSuite.tryRegistration()[pri:3, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="tryRegistration" class="WolframTestSuite.WolframCloudTestSuite"/>
      </group> <!-- functest -->
      <group name="usrexptest">
        <method signature="WolframCloudTestSuite.siteLaunch()[pri:1, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="siteLaunch" class="WolframTestSuite.WolframCloudTestSuite"/>
        <method signature="WolframCloudTestSuite.tryHomescreen()[pri:4, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="tryHomescreen" class="WolframTestSuite.WolframCloudTestSuite"/>
        <method signature="WolframCloudTestSuite.tryLogin()[pri:2, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="tryLogin" class="WolframTestSuite.WolframCloudTestSuite"/>
        <method signature="WolframCloudTestSuite.tryNotebook()[pri:5, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="tryNotebook" class="WolframTestSuite.WolframCloudTestSuite"/>
        <method signature="WolframCloudTestSuite.tryRegistration()[pri:3, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="tryRegistration" class="WolframTestSuite.WolframCloudTestSuite"/>
      </group> <!-- usrexptest -->
    </groups>
    <test name="Default test" duration-ms="7898" started-at="2017-05-30T04:40:01Z" finished-at="2017-05-30T04:40:09Z">
      <class name="WolframTestSuite.WolframCloudTestSuite">
        <test-method status="PASS" signature="setUp()[pri:0, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="setUp" is-config="true" duration-ms="3280" started-at="2017-05-29T23:39:58Z" finished-at="2017-05-29T23:40:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="siteLaunch()[pri:1, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="siteLaunch" duration-ms="7845" started-at="2017-05-29T23:40:01Z" finished-at="2017-05-29T23:40:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- siteLaunch -->
        <test-method status="FAIL" signature="tryLogin()[pri:2, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="tryLogin" duration-ms="2" started-at="2017-05-29T23:40:09Z" finished-at="2017-05-29T23:40:09Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at WolframTestSuite.WolframCloudTestSuite.tryLogin(WolframCloudTestSuite.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tryLogin -->
        <test-method status="FAIL" signature="tryRegistration()[pri:3, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="tryRegistration" duration-ms="7" started-at="2017-05-29T23:40:09Z" finished-at="2017-05-29T23:40:09Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at WolframTestSuite.WolframCloudTestSuite.tryRegistration(WolframCloudTestSuite.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tryRegistration -->
        <test-method status="FAIL" signature="tryHomescreen()[pri:4, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="tryHomescreen" duration-ms="12" started-at="2017-05-29T23:40:09Z" finished-at="2017-05-29T23:40:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Home - Wolfram Programming Cloud] but found [Wolfram Cloud]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Home - Wolfram Programming Cloud] but found [Wolfram Cloud]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at WolframTestSuite.WolframCloudTestSuite.tryHomescreen(WolframCloudTestSuite.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tryHomescreen -->
        <test-method status="FAIL" signature="tryNotebook()[pri:5, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="tryNotebook" duration-ms="2" started-at="2017-05-29T23:40:09Z" finished-at="2017-05-29T23:40:09Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at WolframTestSuite.WolframCloudTestSuite.tryNotebook(WolframCloudTestSuite.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tryNotebook -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:WolframTestSuite.WolframCloudTestSuite@34ce8af7]" name="cleanUp" is-config="true" duration-ms="1047" started-at="2017-05-29T23:40:09Z" finished-at="2017-05-29T23:40:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- WolframTestSuite.WolframCloudTestSuite -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
